product-service:
  prodId: 3
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
